
-- Users table (create this first)
CREATE TABLE users (
    id INT  PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
)
-- 1. Grocery
CREATE TABLE grocery (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    weight VARCHAR(50),
    image VARCHAR(255)
);

-- 2. Vegetables
CREATE TABLE vegetables (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    weight VARCHAR(50),
    image VARCHAR(255)
);

-- 3. Cold Drinks
CREATE TABLE cold_drinks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    weight VARCHAR(50),
    image VARCHAR(255)
);

-- 4. Animal Food
CREATE TABLE animal_food (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    weight VARCHAR(50),
    image VARCHAR(255)
);

-- 5. Stationery
CREATE TABLE stationery (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    weight VARCHAR(50),
    image VARCHAR(255)
);

-- 1. Grocery
ALTER TABLE grocery
    ADD COLUMN userId INT,
    ADD CONSTRAINT fk_grocery_user
        FOREIGN KEY (userId) REFERENCES users(id);

-- 2. Vegetables
ALTER TABLE vegetables
    ADD COLUMN userId INT,
    ADD CONSTRAINT fk_vegetables_user
        FOREIGN KEY (userId) REFERENCES users(id);

-- 3. Cold Drinks
ALTER TABLE cold_drinks
    ADD COLUMN userId INT,
    ADD CONSTRAINT fk_cold_drinks_user
        FOREIGN KEY (userId) REFERENCES users(id);

-- 4. Animal Food
ALTER TABLE animal_food
    ADD COLUMN userId INT,
    ADD CONSTRAINT fk_animal_food_user
        FOREIGN KEY (userId) REFERENCES users(id);

-- 5. Stationery
ALTER TABLE stationery
    ADD COLUMN userId INT,
    ADD CONSTRAINT fk_stationery_user
        FOREIGN KEY (userId) REFERENCES users(id);



        ALTER TABLE users        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE grocery      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE vegetables   ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE cold_drinks  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE animal_food  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE stationery   ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER table users
ADD column reset_token  text,
ADD column reset_token_expires TIMESTAMP
ALTER TABLE users
ADD COLUMN google_id VARCHAR(255),

ALTER TABLE users
ALTER COLUMN password DROP NOT NULL;